import re

DEFAULT_SECRET_PATTERNS: list[tuple[str, re.Pattern[str], float]] = [
    ("AWS Access Key", re.compile(r"AKIA[0-9A-Z]{16}"), 0.95),
    ("AWS Secret Key", re.compile(r"(?i)aws_?secret_?access_?key\s*[=:]\s*[a-z0-9/+=]{40}"), 0.95),
    ("GitHub Personal Token", re.compile(r"ghp_\w{36,}"), 0.95),
    ("GitHub Server Token", re.compile(r"ghs_\w{36,}"), 0.95),
    ("GitHub OAuth Token", re.compile(r"gho_\w{36,}"), 0.95),
    ("GitHub User Token", re.compile(r"ghu_\w{36,}"), 0.95),
    ("GitHub App Token", re.compile(r"ghr_\w{36,}"), 0.95),
    ("GitHub Fine-Grained Token", re.compile(r"github_pat_\w{22,}"), 0.95),
    ("GitLab Token", re.compile(r"glpat-[\w-]{20,}"), 0.95),
    ("Slack Bot Token", re.compile(r"xoxb-[\w-]{10,}"), 0.90),
    ("Slack User Token", re.compile(r"xoxp-[\w-]{10,}"), 0.90),
    ("Slack App Token", re.compile(r"xapp-[\w-]{10,}"), 0.90),
    ("Slack Legacy Token", re.compile(r"xoxa-[\w-]{10,}"), 0.90),
    ("Slack Webhook", re.compile(r"https://hooks\.slack\.com/services/T[A-Z0-9]+/B[A-Z0-9]+/[A-Za-z0-9]+"), 0.95),
    ("OpenAI API Key", re.compile(r"sk-[a-zA-Z0-9]{20,}"), 0.90),
    ("Stripe Live Key", re.compile(r"sk_live_[0-9a-zA-Z]{24,}"), 0.95),
    ("Stripe Publishable Key", re.compile(r"pk_live_[0-9a-zA-Z]{24,}"), 0.90),
    ("Discord Bot Token", re.compile(r"[MN][\w-]{23,25}\.[\w-]{6,7}\.[\w-]{27}"), 0.90),
    ("Twilio Account SID", re.compile(r"AC\w{32}"), 0.90),
    ("SendGrid API Key", re.compile(r"SG\.[\w-]{22,}"), 0.90),
    ("Bearer Token", re.compile(r"(?i)bearer\s+[a-z0-9\-._~+/]+=*"), 0.70),
    ("Authorization Header", re.compile(r"(?i)authorization\s*[=:]\s*['\"]?Bearer\s+[a-z0-9\-._~+/]+=*"), 0.80),
    ("Generic API Key", re.compile(r"(?i)api[_-]?key\s*[=:]\s*['\"]?[a-z0-9\-._]{20,}"), 0.80),
    ("Generic Secret", re.compile(r"(?i)(secret|password|passwd|pwd)\s*[=:]\s*['\"]?[^\s'\"]{8,}"), 0.75),
    ("Azure Key", re.compile(r"(?i)(azure|az)[_-]?(key|secret|token)\s*[=:]\s*['\"]?[a-z0-9+/=]{20,}"), 0.85),
    ("GCP API Key", re.compile(r"AIza[\w-]{35}"), 0.90),
    ("Private Key", re.compile(r"-----BEGIN\s+(RSA |EC |DSA |OPENSSH )?PRIVATE KEY-----"), 0.99),
    ("SSH Public Key", re.compile(r"ssh-(rsa|ed25519|dss)\s+[A-Za-z0-9+/=]{20,}"), 0.85),
    ("Certificate", re.compile(r"-----BEGIN\s+CERTIFICATE-----"), 0.85),
    ("PGP Key", re.compile(r"-----BEGIN\s+PGP\s+(PUBLIC|PRIVATE)\s+KEY\s+BLOCK-----"), 0.90),
    ("Connection String", re.compile(r"(?i)(mongodb|postgres|mysql|redis)://[^\s]{10,}"), 0.85),
    ("JWT Token", re.compile(r"eyJ[A-Za-z0-9_-]{10,}\.eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}"), 0.80),
]
