version = 1
SPDX-PackageName = "cerbia"
SPDX-PackageSupplier = "2026 INDUSTRIA DE DISEÑO TEXTIL S.A. (INDITEX S.A.)"
SPDX-PackageDownloadLocation = "https://github.com/InditexTech/cerbia"

[[annotations]]
path = [
    "repolinter.json",
    "NOTICE",
    ".gitignore",
    ".github/CODEOWNERS",
    ".pre-commit-config.yaml",
    ".python-version",
    "Makefile",
    "CHANGELOG.md",
    "pyproject.toml",
    "uv.lock",
    "docs/**",
    "examples/**",
    "packages/**",
    "scripts/**",
]
SPDX-FileCopyrightText = "2026 INDUSTRIA DE DISEÑO TEXTIL S.A. (INDITEX S.A.)"
SPDX-License-Identifier = "Apache-2.0"
