import re
from pathlib import Path
from typing import Annotated
from urllib.request import urlopen

import typer

_DEFAULT_LANGUAGES = ["en", "es", "gl"]
_PROFILE_PATTERN = re.compile(r'"(?P<language>en|es|gl)"\s*:\s*\[(?P<values>[^]]+)\]')
_DEFAULT_OUTPUT = (
    Path(__file__).parent.parent
    / "packages"
    / "cerbia-core"
    / "src"
    / "cerbia"
    / "core"
    / "i18n"
    / "language_profiles.py"
)
_HEADER_TEXT = """\"\"\"CyberChef byte-frequency profiles for speculative decoding.

Generated by ``scripts/generate_language_profiles.py`` from GCHQ CyberChef (https://github.com/gchq/cyberchef) revision
``{revision}``:

The ``en``, ``es``, and ``gl`` tables are 256-byte frequency profiles based on the byte-frequency methodology used by
the Magic operation in GCHQ's CyberChef.

The corresponding CyberChef Magic methodology documentation is available at
https://github.com/gchq/CyberChef/wiki/Automatic-detection-of-encoded-data-using-CyberChef-Magic#byte-frequency-analysis

Each profile is a tuple whose position is the byte value: index ``0`` represents ``0x00`` and index ``255``
represents ``0xFF``. Each entry is a normalized frequency on the ``[0.0, 1.0]`` probability scale for that byte in the
corresponding language profile.

The values are not character-code lookups and must be interpreted as byte-level weights. The tables intentionally retain
the full 256-byte domain, including control bytes and the individual bytes that make up multi-byte UTF-8 sequences.

The profiles are the current defaults for speculative decoding. The scoring path builds observed byte-frequency
information from candidate bytes and compares it with the available language profiles to produce language-fit statistics
used when ranking and accepting speculative decode branches.

The numerical tables in this file were copied from GCHQ CyberChef's Magic.mjs at revision
{revision}. CyberChef percentage values are divided by 100 and stored as
``[0.0, 1.0]`` byte-frequency values for use in CerbIA.

Original work authored by n1474335 <n1474335@gmail.com>. Crown Copyright 2018. Licensed under the Apache License,
Version 2.0.

This file has been modified by Inditex for incorporation into CerbIA.
\"\"\"

from typing import Final

LANGUAGE_PROFILES: Final[dict[str, tuple[float, ...]]] = {{
{profiles}
}}
"""


def _parse_profiles(magic_source: str, languages: list[str]) -> dict[str, tuple[float, ...]]:
    percent_profiles = {
        match["language"]: tuple(float(value) for value in match["values"].split(","))
        for match in _PROFILE_PATTERN.finditer(magic_source)
    }

    profiles = {language: tuple(value / 100 for value in percent_profiles[language]) for language in languages}
    for language, profile in profiles.items():
        if len(profile) != 256:
            msg = f"CyberChef {language!r} profile has {len(profile)} values; expected 256"
            raise RuntimeError(msg)

        if any(value < 0.0 for value in profile):
            msg = f"CyberChef {language!r} profile contains a negative value"
            raise RuntimeError(msg)

    return profiles


def _render_module(profiles: dict[str, tuple[float, ...]], revision: str, languages: list[str]) -> str:
    profile_lines: list[str] = []
    for language in languages:
        values = "\n".join(f"        {value!r}," for value in profiles[language])
        profile_lines.append(f'    "{language}": (\n{values}\n    ),')

    return _HEADER_TEXT.format(revision=revision, profiles=chr(10).join(profile_lines))


def _fetch_source(revision: str) -> str:
    url = f"https://raw.githubusercontent.com/gchq/CyberChef/{revision}/src/core/lib/Magic.mjs"
    with urlopen(url, timeout=30) as response:
        source = response.read().decode("utf-8")

    return source


def main(
    revision: Annotated[str, typer.Option(help="CyberChef revision to fetch.")],
    language: Annotated[
        list[str], typer.Option(help="Languages to include in the generated module.")
    ] = _DEFAULT_LANGUAGES,
    output: Annotated[Path, typer.Option(help="Path for the generated Python module.")] = _DEFAULT_OUTPUT,
) -> None:
    """Fetch CyberChef's profiles and write the formatted runtime module."""
    source = _fetch_source(revision)
    profiles = _parse_profiles(source, language)
    module_text = _render_module(profiles, revision, language)

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(module_text, encoding="utf-8")


if __name__ == "__main__":
    typer.run(main)
