site:
  title: CerbIA
  url: https://inditextech.github.io/cerbia
  start_page: ROOT::index.adoc
  keys:
    product-logo: /cerbia-logo.png
    product-logo-dark: /cerbia-logo.png
    favicon: /favicon.png
content:
  sources:
    - url: ..
      start_path: docs/src
      branches: HEAD
ui:
  bundle:
    url: ./node_modules/@inditextech/docouture-ui-bundle/build/ui-bundle.zip
    snapshot: false
  supplemental_files: ./supplemental-ui
output:
  dir: build/site
urls:
  html_extension_style: indexify
runtime:
  log:
    failure_level: warn
    level: info
asciidoc:
  attributes:
    experimental: ''
    icons: font
    kroki-enabled: true
    kroki-diagram-types: mermaid
    sectanchors: ''
    idprefix: ''
    idseparator: '-'
    source-highlighter: shiki
    page-pagination: '@'
  extensions:
    - '@inditextech/docouture-asciidoc-extensions'
    - ./scripts/migration/diagram-accessibility.cjs
antora:
  extensions:
    - require: '@inditextech/docouture-antora-extensions'
      changelog_path: ../CHANGELOG.md
