# SPDX-FileCopyrightText: 2026 INDUSTRIA DE DISEÑO TEXTIL S.A. (INDITEX S.A.)
# SPDX-License-Identifier: Apache-2.0

name: code-uv-PR-verify

concurrency:
  group: code-PR-verify-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read

on:
  pull_request:
  workflow_dispatch:

jobs:
  repo-linter:
    name: Repo Linter
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: 'Run Repolinter'
        uses: newrelic/repolinter-action@3f4448f855c351e9695b24524a4111c7847b84cb # v1.7.0

  reuse-compliance:
    name: REUSE Compliance
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@bb774aa972c2a89ff34781233d275075cbddf542 # v5

  conventional-commits:
    name: Conventional Commits
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: webiny/action-conventional-commits@8bc41ff4e7d423d56fa4905f6ff79209a78776c7 # v1.3.0

  prepare:
    name: Prepare
    runs-on: ubuntu-24.04
    outputs:
      packages: ${{ steps.discover.outputs.packages }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Setup Python project
        uses: ./.github/actions/setup-python-project
        with:
          check-lock: 'true'

      - name: Discover packages
        id: discover
        run: |
          uv run --locked scripts/list_packages.py --gh-output-key packages

  verify:
    name: Verify - ${{ matrix.package }}
    needs: prepare
    runs-on: ubuntu-24.04
    env:
      PACKAGE: ${{ matrix.package }}
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJSON(needs.prepare.outputs.packages) }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Python project
        uses: ./.github/actions/setup-python-project

      - name: Run lint
        run: make lint "$PACKAGE"

      - name: Run test
        run: make test "$PACKAGE"

      - name: Run build
        run: make build "$PACKAGE"
