# SPDX-FileCopyrightText: 2026 INDUSTRIA DE DISEÑO TEXTIL S.A. (INDITEX S.A.)
# SPDX-License-Identifier: Apache-2.0

name: docs-npm-verify

on:
  pull_request:
    branches: ['main', 'main-*']
    paths: ['docs/**']

permissions:
  contents: read

concurrency:
  group: "docs-verify-${{ github.ref }}"
  cancel-in-progress: false

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Use Node 22
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '22'
          cache: npm
          cache-dependency-path: docs/package-lock.json

      - name: Build documentation
        run: make docs-build
